// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async chatStream(payload: ChatPayload, onEvent: TAURI_CHANNEL<StreamChunk>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_stream", { payload, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countTokens(conversationId: string) : Promise<Result<TokenUsage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_tokens", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startChatServer(modelPath: string, contextSize: number, template: string | null, mmproj: string | null, exposeNetwork: boolean | null, mlock: boolean | null, quantizeKv: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_chat_server", { modelPath, contextSize, template, mmproj, exposeNetwork, mlock, quantizeKv }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopChatServer(modelPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_chat_server", { modelPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startEmbeddingServer(modelPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_embedding_server", { modelPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSummarizerServer(modelPath: string, contextSize: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_summarizer_server", { modelPath, contextSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSidecarStatus() : Promise<SidecarStatus> {
    return await TAURI_INVOKE("get_sidecar_status");
},
async getChatServerConfig() : Promise<ChatServerConfig | null> {
    return await TAURI_INVOKE("get_chat_server_config");
},
async startSttServer(modelPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_stt_server", { modelPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startImageServer(modelPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_image_server", { modelPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTtsServer(modelPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_tts_server", { modelPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelGeneration() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_generation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkWebSearch(query: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_web_search", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateImage(params: ImageGenParams) : Promise<Result<ImageResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_image", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(audioBytes: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioBytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ingestDocument(filePath: string, chatId: string | null, projectId: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ingest_document", { filePath, chatId, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadDocument(fileBytes: number[], filename: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_document", { fileBytes, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retrieveContext(query: string, chatId: string | null, docIds: string[] | null, projectId: string | null) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retrieve_context", { query, chatId, docIds, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkVectorIndexIntegrity() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_vector_index_integrity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels() : Promise<Result<ModelFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(url: string, filename: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { url, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkModelPath(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("check_model_path", { path });
},
async openModelsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_models_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLocalModel(filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_local_model", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkMissingStandardAssets() : Promise<Result<StandardAsset[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_missing_standard_assets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadStandardAsset(filename: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_standard_asset", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openStandardModelsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_standard_models_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelMetadata(path: string) : Promise<Result<GGUFMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversations() : Promise<Result<Conversation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openConfigFile() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_config_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUserConfig() : Promise<UserConfig> {
    return await TAURI_INVOKE("get_user_config");
},
async updateUserConfig(config: UserConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_user_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHfToken() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hf_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createConversation(title: string, projectId: string | null) : Promise<Result<Conversation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_conversation", { title, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMessages(conversationId: string) : Promise<Result<FrontendMessage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_messages", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveMessage(conversationId: string, role: string, content: string, images: string[] | null, attachedDocs: AttachedDoc[] | null, webSearchResults: WebSearchResult[] | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_message", { conversationId, role, content, images, attachedDocs, webSearchResults }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editMessage(messageId: string, newContent: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_message", { messageId, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConversationTitle(id: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conversation_title", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConversationProject(id: string, projectId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conversation_project", { id, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConversationsOrder(orders: ([string, number])[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conversations_order", { orders }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAllHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_all_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadImage(imageBytes: number[]) : Promise<Result<ImageResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_image", { imageBytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadImage(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_image", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImagePath(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_path", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openImagesFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_images_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemSpecs() : Promise<SystemSpecs> {
    return await TAURI_INVOKE("get_system_specs");
},
async createProject(request: CreateProjectRequest) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<Project[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProject(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProject(id: string, name: string | null, description: string | null) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project", { id, name, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProjectsOrder(orders: ([string, number])[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_projects_order", { orders }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectDocuments(projectId: string) : Promise<Result<Document[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_documents", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDocument(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rigCheckWebSearch(query: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rig_check_web_search", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentChat(request: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_chat", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Clawdbot status
 */
async getClawdbotStatus() : Promise<Result<ClawdbotStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clawdbot_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Slack configuration
 */
async saveAnthropicKey(key: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_anthropic_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Anthropic API key
 */
async getAnthropicKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_anthropic_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Brave Search API key
 */
async saveBraveKey(key: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_brave_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Brave Search API key
 */
async getBraveKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_brave_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save OpenAI API key
 */
async saveOpenaiKey(key: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_openai_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get OpenAI API key
 */
async getOpenaiKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_openai_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save OpenRouter API key
 */
async saveOpenrouterKey(key: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_openrouter_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get OpenRouter API key
 */
async getOpenrouterKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_openrouter_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Gemini API key
 */
async saveGeminiKey(key: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_gemini_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Gemini API key
 */
async getGeminiKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Groq API key
 */
async saveGroqKey(key: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_groq_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Groq API key
 */
async getGroqKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_groq_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save selected cloud model
 */
async saveSelectedCloudModel(model: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_selected_cloud_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle secret access for OpenClaw
 */
async clawdbotToggleSecretAccess(secret: string, granted: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_toggle_secret_access", { secret, granted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSlackConfig(configInput: SlackConfigInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_slack_config", { configInput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Telegram configuration
 */
async saveTelegramConfig(configInput: TelegramConfigInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_telegram_config", { configInput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Gateway configuration
 */
async saveGatewaySettings(mode: string, url: string | null, token: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_gateway_settings", { mode, url, token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start Clawdbot gateway (spawns moltbot binary and connects WS client)
 */
async startClawdbotGateway() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_clawdbot_gateway") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop Clawdbot gateway (stops WS client and moltbot process)
 */
async stopClawdbotGateway() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_clawdbot_gateway") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Clawdbot sessions list
 */
async getClawdbotSessions() : Promise<Result<ClawdbotSessionsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clawdbot_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClawdbotHistory(sessionKey: string, limit: number, before: string | null) : Promise<Result<ClawdbotHistoryResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clawdbot_history", { sessionKey, limit, before }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a Clawdbot session
 */
async deleteClawdbotSession(sessionKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_clawdbot_session", { sessionKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a message to a Clawdbot session
 */
async sendClawdbotMessage(sessionKey: string, text: string, deliver: boolean) : Promise<Result<ClawdbotRpcResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_clawdbot_message", { sessionKey, text, deliver }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Subscribe to a Clawdbot session for live updates
 */
async subscribeClawdbotSession(sessionKey: string) : Promise<Result<ClawdbotRpcResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_clawdbot_session", { sessionKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abort a running chat
 */
async abortClawdbotChat(sessionKey: string, runId: string | null) : Promise<Result<ClawdbotRpcResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_clawdbot_chat", { sessionKey, runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve an approval request
 */
async resolveClawdbotApproval(approvalId: string, approved: boolean) : Promise<Result<ClawdbotRpcResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_clawdbot_approval", { approvalId, approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get gateway diagnostic info
 */
async getClawdbotDiagnostics() : Promise<Result<ClawdbotDiagnostics, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clawdbot_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear Clawdbot memory (deletes memory directory or identity files)
 */
async clearClawdbotMemory(target: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_clawdbot_memory", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Clawdbot memory content (MEMORY.md)
 */
async getClawdbotMemory() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clawdbot_memory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get contents of a specific file in the Clawdbot workspace (e.g. SOUL.md)
 */
async getClawdbotFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clawdbot_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write content to a specific file in the Clawdbot workspace
 */
async writeClawdbotFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_clawdbot_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save Clawdbot memory content (MEMORY.md)
 */
async saveClawdbotMemory(content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_clawdbot_memory", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all markdown files in the Clawdbot workspace root and memory/ subdirectory
 */
async listWorkspaceFiles() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspace_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotCronList() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_cron_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotCronRun(key: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_cron_run", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotCronHistory(key: string, limit: number) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_cron_history", { key, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotSkillsList() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_skills_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotSkillsStatus() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_skills_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotSkillsToggle(key: string, enabled: boolean) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_skills_toggle", { key, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotInstallSkillRepo(repoUrl: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_install_skill_repo", { repoUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotInstallSkillDeps(name: string, installId: string | null) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_install_skill_deps", { name, installId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotConfigSchema() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_config_schema") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotConfigGet() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_config_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotConfigSet(key: string, value: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_config_set", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotConfigPatch(patch: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_config_patch", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotSystemPresence() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_system_presence") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotLogsTail(limit: number) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_logs_tail", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotUpdateRun() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_update_run") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotWebLoginWhatsapp() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_web_login_whatsapp") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotWebLoginTelegram() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_web_login_telegram") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a custom secret
 */
async addCustomSecret(name: string, value: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_secret", { name, value, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a custom secret
 */
async removeCustomSecret(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_custom_secret", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle custom secret access for OpenClaw
 */
async clawdbotToggleCustomSecret(id: string, granted: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_toggle_custom_secret", { id, granted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle node host (OS automation) for OpenClaw
 */
async clawdbotToggleNodeHost(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_toggle_node_host", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle local inference (exposing local LLM) for OpenClaw
 */
async clawdbotToggleLocalInference(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_toggle_local_inference", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotToggleExposeInference(enabled: boolean) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_toggle_expose_inference", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotSetSetupCompleted(completed: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_set_setup_completed", { completed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clawdbotToggleAutoStart(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clawdbot_toggle_auto_start", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save HuggingFace token
 */
async setHfToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hf_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPermissionStatus() : Promise<PermissionStatus> {
    return await TAURI_INVOKE("get_permission_status");
},
async requestPermission(permission: string) : Promise<void> {
    await TAURI_INVOKE("request_permission", { permission });
},
async toggleSpotlight() : Promise<void> {
    await TAURI_INVOKE("toggle_spotlight");
},
async hideSpotlight() : Promise<void> {
    await TAURI_INVOKE("hide_spotlight");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AttachedDoc = { id: string; name: string }
export type ChatPayload = { model: string; messages: Message[]; temperature: number; top_p: number; web_search_enabled?: boolean; auto_mode?: boolean; project_id: string | null; conversation_id: string | null }
export type ChatServerConfig = { port: number; token: string; context_size: number }
/**
 * Diagnostic info
 */
export type ClawdbotDiagnostics = { timestamp: string; gateway_running: boolean; ws_connected: boolean; version: string; platform: string; port: number | null; state_dir: string | null; slack_enabled: boolean | null; telegram_enabled: boolean | null }
/**
 * Chat history response
 */
export type ClawdbotHistoryResponse = { messages: ClawdbotMessage[]; has_more: boolean }
/**
 * Message in chat history
 */
export type ClawdbotMessage = { id: string; role: string; ts_ms: number; text: string; source: string | null }
/**
 * RPC result response
 */
export type ClawdbotRpcResponse = { ok: boolean; message: string | null }
/**
 * Session info from gateway
 */
export type ClawdbotSession = { session_key: string; title: string | null; updated_at_ms: number | null; source: string | null }
/**
 * Sessions list response
 */
export type ClawdbotSessionsResponse = { sessions: ClawdbotSession[] }
/**
 * Clawdbot status response
 */
export type ClawdbotStatus = { gateway_running: boolean; ws_connected: boolean; slack_enabled: boolean; telegram_enabled: boolean; port: number; gateway_mode: string; remote_url: string | null; remote_token: string | null; device_id: string; auth_token: string; state_dir: string; has_huggingface_token: boolean; huggingface_granted: boolean; has_anthropic_key: boolean; anthropic_granted: boolean; has_brave_key: boolean; brave_granted: boolean; has_openai_key: boolean; openai_granted: boolean; has_openrouter_key: boolean; openrouter_granted: boolean; has_gemini_key: boolean; gemini_granted: boolean; has_groq_key: boolean; groq_granted: boolean; custom_secrets: CustomSecret[]; node_host_enabled: boolean; local_inference_enabled: boolean; selected_cloud_brain: string | null; selected_cloud_model: string | null; setup_completed: boolean; auto_start_gateway: boolean }
export type Conversation = { id: string; title: string; created_at: number; updated_at: number; project_id: string | null; sort_order: number }
export type CreateProjectRequest = { name: string; description: string | null }
export type CustomPersona = { id: string; name: string; description: string; instructions: string }
export type CustomSecret = { id: string; name: string; value: string; description: string | null; granted: boolean }
export type Document = { id: string; path: string; status: string; created_at: number; updated_at: number; project_id: string | null }
export type FrontendMessage = { id: string; conversation_id: string; role: string; content: string; images: string[] | null; attached_docs: AttachedDoc[] | null; web_search_results: WebSearchResult[] | null; created_at: number }
export type GGUFMetadata = { architecture: string; context_length: number; embedding_length: number; block_count: number; head_count: number; head_count_kv: number; file_type: number }
export type ImageGenParams = { prompt: string; model: string | null; vae: string | null; clip_l: string | null; clip_g: string | null; t5xxl: string | null; negative_prompt: string | null; width: number | null; height: number | null; steps: number | null; cfg_scale: number | null; seed: number; schedule: string | null; sampling_method: string | null }
export type ImageResponse = { id: string; path: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type KnowledgeBit = { id: string; label: string; content: string; enabled: boolean }
export type Message = { role: string; content: string; images: string[] | null; attached_docs: AttachedDoc[] | null; is_summary: boolean | null; original_messages: Message[] | null }
export type ModelFile = { name: string; size: number; path: string }
export type PermissionStatus = { accessibility: boolean; screen_recording: boolean }
export type Project = { id: string; name: string; description: string | null; created_at: number; updated_at: number; sort_order: number }
export type SidecarStatus = { chat_running: boolean; embedding_running: boolean; stt_running: boolean; tts_running: boolean; image_running: boolean; summarizer_running: boolean }
/**
 * Slack configuration input
 */
export type SlackConfigInput = { enabled: boolean; bot_token: string | null; app_token: string | null }
export type StandardAsset = { name: string; category: string; filename: string; url: string; size: number }
export type StreamChunk = { content: string; done: boolean; usage: TokenUsage | null; context_update: Message[] | null }
export type SystemSpecs = { total_memory: number; used_memory: number; cpu_brand: string; cpu_usage: number; cpu_cores: number; platform: string; app_memory: number; memory_bandwidth_gbps: number }
export type TAURI_CHANNEL<TSend> = null
/**
 * Telegram configuration input
 */
export type TelegramConfigInput = { enabled: boolean; bot_token: string | null; dm_policy: string; groups_enabled: boolean }
export type TokenUsage = { prompt_tokens: number; completion_tokens: number; total_tokens: number }
export type UserConfig = { search_concurrency_limit?: number; scrape_concurrency_limit?: number; max_search_results?: number; max_scrape_chars?: number; scrape_timeout_secs?: number; default_context_window?: number; summarization_chunk_size?: number; llm_temperature?: number; llm_top_p?: number; vector_dimensions?: number; sd_threads?: number; knowledge_bits?: KnowledgeBit[]; custom_personas?: CustomPersona[]; image_prompt_enhance_enabled?: boolean; selected_persona?: string; selected_chat_provider?: string | null; memory_reservation_gb?: number; enable_memory_reservation?: boolean; mlock?: boolean; quantize_kv?: boolean; spotlight_shortcut?: string }
export type WebSearchResult = { title: string; link: string; snippet: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
