use super::*;
use serde::{Deserialize, Serialize};

/// Result of the agentic loop execution.
pub(crate) enum AgenticLoopResult {
    /// Completed with a response (needs to be sent to channel by caller).
    Response(thinclaw_agent::submission::AgentResponsePayload),
    /// Completed and response was already streamed to the channel via
    /// progressive edits (sendMessage + editMessageText).  Caller should
    /// NOT send it again — only persist and update thread state.
    Streamed(thinclaw_agent::submission::AgentResponsePayload),
    /// A tool requires approval before continuing.
    NeedApproval {
        /// The pending approval request to store.
        pending: PendingApproval,
    },
}

impl AgenticLoopResult {
    pub(crate) fn with_generated_attachments(
        mut self,
        attachments: &[thinclaw_media::MediaContent],
    ) -> Self {
        match &mut self {
            Self::Response(payload) | Self::Streamed(payload) => {
                crate::agent::outbound_media::dedupe_extend(
                    &mut payload.attachments,
                    attachments.to_vec(),
                );
            }
            Self::NeedApproval { .. } => {}
        }
        self
    }
}

/// Per-turn mutable state threaded through `run_agentic_loop` and the
/// phases it calls (tool execution, advisor auto-consultation, etc.).
///
/// Bundling these fields keeps helper signatures from growing a mutable
/// parameter per piece of state — they take `&mut TurnState` instead.
///
/// `Serialize`/`Deserialize` are derived so this state is a serializable
/// unit (a future step for mid-turn persistence); that persistence is not
/// implemented yet. `generated_attachments` is skipped because
/// `thinclaw_media::MediaContent` does not derive serde — it round-trips
/// as empty on deserialize, which is acceptable since attachments are
/// regenerated by tool execution, not replayed from a snapshot.
#[derive(Debug, Serialize, Deserialize)]
pub(super) struct TurnState {
    /// The evolving LLM conversation context for this turn.
    pub(super) context_messages: Vec<ChatMessage>,
    /// Media attachments produced by tool calls during this turn, merged
    /// into the final response.
    #[serde(skip)]
    pub(super) generated_attachments: Vec<thinclaw_media::MediaContent>,
    /// Signature of the most recent tool-call set, for stuck-loop detection.
    pub(super) last_call_signature: Option<u64>,
    /// Count of consecutive iterations with the same tool-call signature.
    pub(super) consecutive_same_calls: u32,
    /// Whether the pre-compaction memory flush has already fired this
    /// compaction cycle.
    pub(super) memory_flush_fired: bool,
    /// The last model override applied via `llm_select`, if any.
    pub(super) last_applied_model_override: Option<String>,
    /// Advisor auto-consultation checkpoint/failure tracking for this turn.
    pub(super) advisor_state: AdvisorTurnState,
}

#[derive(Clone)]
pub(super) struct LlmTurnOptions {
    pub(super) force_text: bool,
    pub(super) thinking: crate::llm::ThinkingConfig,
    pub(super) context_documents: Vec<String>,
    pub(super) stream_to_user: bool,
    pub(super) emit_progress_status: bool,
    pub(super) emit_thinking_status: bool,
    pub(super) planning_mode: bool,
    pub(super) max_output_tokens: Option<u32>,
}

pub(super) struct LlmTurnResult {
    pub(super) output: RespondOutput,
    pub(super) streamed_text: bool,
}

#[cfg(test)]
pub(super) use thinclaw_agent::dispatcher_policy::TOOL_PHASE_NO_TOOLS_SENTINEL;
pub(super) use thinclaw_agent::dispatcher_policy::{
    ADVISOR_BLOCKED_SYSTEM_PROMPT, ADVISOR_BLOCKED_TOOL_RESULT_MESSAGE,
    AdvisorAutoEscalationPolicyMode, AdvisorAutoTrigger, AdvisorFailureContext, AdvisorTurnState,
    ContextCapDecision, DispatcherRuntimePolicyStatus, FinalizationFailureKind,
    ITERATION_LIMIT_NUDGE_PROMPT, IterationLimitPolicy, LlmTurnErrorKind,
    MEMORY_FLUSH_ALLOWED_TOOLS, ModelOverrideActivationDecision, STUCK_LOOP_FINALIZATION_PROMPT,
    STUCK_LOOP_NUDGE_PROMPT, StuckLoopDecision, TOOL_PHASE_PLANNING_MAX_TOKENS,
    TOOL_PHASE_PLANNING_PROMPT, TOOL_PHASE_SYNTHESIS_PROMPT, TOOL_RESULT_KEEP_TURNS,
    ToolPhaseTextOutcome, context_cap_decision_with_history_budget,
    decide_model_override_activation, failed_model_override_reset_note,
    finalization_failure_response, memory_flush_due,
    should_hold_complex_final_pass as policy_should_hold_complex_final_pass,
    should_merge_tool_output_attachments, stuck_loop_decision, tool_call_signature,
    tool_result_indicates_failure, tool_result_prune_boundary, transient_llm_retry_delay,
    unsupported_model_override_note, update_stuck_loop_signature,
};
