/**
 * guards.ts — Runtime null/undefined guards for Tauri binding consumers.
 *
 * `bindings.ts` is auto-generated by tauri-specta.  Every Rust `Option<T>`
 * surfaces as `T | null` in TypeScript.  These helpers make consuming
 * nullable fields safe and explicit, replacing unguarded `!` operators and
 * silent `undefined` coercions throughout the frontend.
 *
 * Usage:
 *   import { defined, withDefault } from "@/lib/guards";
 *
 *   // Throws immediately with a helpful message if value is null/undefined:
 *   const port = defined(cfg.port, "ChatServerConfig.port");
 *
 *   // Returns a fallback instead of throwing:
 *   const title = withDefault(conversation.title, "Untitled");
 */

/**
 * Assert that `value` is neither `null` nor `undefined`.
 *
 * @param value   - The value to check.
 * @param name    - Human-readable identifier used in the error message
 *                  (e.g. `"UserConfig.selected_chat_provider"`).
 * @returns The value, narrowed to `NonNullable<T>`.
 * @throws {Error} If `value` is `null` or `undefined`.
 */
export function defined<T>(value: T | null | undefined, name?: string): NonNullable<T> {
    if (value === null || value === undefined) {
        throw new Error(
            name
                ? `Expected "${name}" to be defined, but received ${String(value)}`
                : `Expected a defined value but received ${String(value)}`
        );
    }
    return value as NonNullable<T>;
}

/**
 * Return `value` if it is not `null`/`undefined`, otherwise return `fallback`.
 *
 * This is a typed alternative to `value ?? fallback` that also accepts `null`
 * (whereas `??` only short-circuits on `null` / `undefined`).
 *
 * @param value    - Potentially null/undefined value from a Tauri binding.
 * @param fallback - Default value to use when `value` is absent.
 * @returns `value` (non-null) or `fallback`.
 */
export function withDefault<T>(value: T | null | undefined, fallback: T): T {
    return value !== null && value !== undefined ? value : fallback;
}

/**
 * Narrow a `Result<T, E>` from the Tauri IPC layer to its `Ok` value.
 *
 * @param result - A `{ status: "ok"; data: T } | { status: "error"; error: E }` result.
 * @param label  - Describes the operation for use in the thrown error message.
 * @returns `result.data` when status is "ok".
 * @throws {Error} when status is "error", with `result.error` stringified.
 */
export function unwrapResult<T, E>(
    result: { status: "ok"; data: T } | { status: "error"; error: E },
    label?: string
): T {
    if (result.status === "ok") {
        return result.data;
    }
    const prefix = label ? `[${label}]` : "[Tauri command]";
    const message =
        typeof result.error === "string"
            ? result.error
            : JSON.stringify(result.error);
    throw new Error(`${prefix} ${message}`);
}
