import type * as thinclaw from '../../../lib/thinclaw';

export const SHELL_PROJECTS: thinclaw.ThinClawRepoProject[] = [
    {
        id: 'shell-thinclaw-desktop',
        name: 'ThinClaw Desktop',
        repo_url: 'github.com/openclaw/thinclaw-desktop',
        default_branch: 'main',
        local_path: '~/Projects/thinclaw-desktop',
        description: 'Desktop app and runtime integration workstream.',
        state: 'setup_required',
        active_runs: 2,
        queued_items: 5,
        open_prs: 1,
        merge_gate_state: 'pending',
        github_app: 'pending',
        docker_agents: 'ready',
        credentials: 'partial',
        concurrency_limit: 3,
        write_mode: 'maintainer_branch_pr',
        auto_merge_policy: 'approved_only',
        notifications: 'enabled',
        updated_at: '2026-06-13T09:42:00Z',
        setup_checklist: [
            { key: 'feature_flag', label: 'Feature flag', state: 'pending', detail: 'Enable repo_projects.enabled before live dispatch' },
            { key: 'github_app', label: 'GitHub App', state: 'pending', detail: 'Installation awaiting repository grant' },
            { key: 'docker_agents', label: 'Docker coding agents', state: 'complete', detail: '3 runners registered' },
            { key: 'coding_backend', label: 'Coding backend', state: 'complete', detail: 'Default backend: worker' },
            { key: 'credentials', label: 'Credentials', state: 'pending', detail: 'CI token missing deploy scope' },
            { key: 'concurrency', label: 'Concurrency', state: 'complete', detail: 'Limit set to 3' },
            { key: 'write_mode', label: 'Write mode', state: 'complete', detail: 'Maintainer branch PR' },
            { key: 'auto_merge_policy', label: 'Auto-merge policy', state: 'complete', detail: 'Approved PRs with green checks' },
            { key: 'notifications', label: 'Notifications', state: 'complete', detail: 'Desktop and Slack enabled' },
        ],
        backlog: [
            { id: 'TC-112', title: 'Wire repo project command bus', priority: 'urgent', state: 'running', owner: 'worker-a', labels: ['frontend'] },
            { id: 'TC-109', title: 'Add merge gate policy preview', priority: 'high', state: 'queued', owner: 'worker-g', labels: ['ui'] },
            { id: 'TC-101', title: 'Persist worker run timeline events', priority: 'medium', state: 'blocked', owner: 'worker-c', labels: ['runtime'] },
            { id: 'TC-097', title: 'Normalize PR approval payloads', priority: 'medium', state: 'queued', owner: null, labels: ['github'] },
        ],
        worker_runs: [
            {
                id: 'run-2841',
                backlog_id: 'TC-112',
                agent: 'docker-agent-01',
                state: 'running',
                branch: 'workers/tc-112-command-bus',
                started_at: '2026-06-13T09:12:00Z',
                duration_secs: 1800,
                last_event: 'Awaiting type contract review',
            },
            {
                id: 'run-2837',
                backlog_id: 'TC-101',
                agent: 'docker-agent-02',
                state: 'paused',
                branch: 'workers/tc-101-timeline',
                started_at: '2026-06-13T08:20:00Z',
                duration_secs: 3540,
                last_event: 'Credential scope missing',
            },
        ],
        pull_requests: [
            { id: 'pr-88', title: 'Repo projects command skeleton', number: 88, branch: 'workers/tc-112-command-bus', state: 'draft', author: 'docker-agent-01' },
        ],
        ci_checks: [
            { id: 'ci-ts', name: 'frontend / typecheck', state: 'passed' },
            { id: 'ci-rust', name: 'backend / cargo test', state: 'running' },
            { id: 'ci-e2e', name: 'desktop / smoke', state: 'queued' },
        ],
        merge_gates: [
            { id: 'gate-github-app', label: 'GitHub App installation', state: 'pending', required: true, detail: 'Repository access not confirmed' },
            { id: 'gate-ci', label: 'Required CI checks', state: 'pending', required: true, detail: '1 running, 1 queued' },
            { id: 'gate-review', label: 'Human approval', state: 'blocked', required: true, detail: 'Review requested' },
        ],
    },
    {
        id: 'shell-runtime-contracts',
        name: 'Runtime Contracts',
        repo_url: 'github.com/openclaw/runtime-contracts',
        default_branch: 'main',
        description: 'Shared command contracts for desktop agents.',
        state: 'ready',
        active_runs: 0,
        queued_items: 2,
        open_prs: 0,
        merge_gate_state: 'passed',
        github_app: 'connected',
        docker_agents: 'ready',
        credentials: 'ready',
        concurrency_limit: 2,
        write_mode: 'fork_pr',
        auto_merge_policy: 'manual',
        notifications: 'enabled',
        updated_at: '2026-06-13T08:15:00Z',
        setup_checklist: [
            { key: 'feature_flag', label: 'Feature flag', state: 'complete', detail: 'Supervisor enabled' },
            { key: 'github_app', label: 'GitHub App', state: 'complete', detail: 'Installed' },
            { key: 'docker_agents', label: 'Docker coding agents', state: 'complete', detail: '2 runners registered' },
            { key: 'coding_backend', label: 'Coding backend', state: 'complete', detail: 'Default backend: worker' },
            { key: 'credentials', label: 'Credentials', state: 'complete', detail: 'All scopes present' },
            { key: 'concurrency', label: 'Concurrency', state: 'complete', detail: 'Limit set to 2' },
            { key: 'write_mode', label: 'Write mode', state: 'complete', detail: 'Fork PR' },
            { key: 'auto_merge_policy', label: 'Auto-merge policy', state: 'pending', detail: 'Manual merge required' },
            { key: 'notifications', label: 'Notifications', state: 'complete', detail: 'Desktop enabled' },
        ],
        backlog: [
            { id: 'RC-031', title: 'Generate merge gate schema', priority: 'high', state: 'queued', owner: null, labels: ['schema'] },
            { id: 'RC-024', title: 'Document run cancellation payload', priority: 'low', state: 'queued', owner: null, labels: ['docs'] },
        ],
        worker_runs: [],
        pull_requests: [],
        ci_checks: [
            { id: 'ci-contracts', name: 'contracts / check', state: 'passed' },
            { id: 'ci-schema', name: 'schema / snapshot', state: 'passed' },
        ],
        merge_gates: [
            { id: 'gate-ci', label: 'Required CI checks', state: 'passed', required: true },
            { id: 'gate-policy', label: 'Merge policy', state: 'passed', required: true, detail: 'Manual merge' },
        ],
    },
];
export const SHELL_EVENTS: thinclaw.ThinClawJobEvent[] = [
    {
        id: 'event-setup',
        event_type: 'repo.project.setup.pending',
        created_at: '2026-06-13T09:42:00Z',
        data: { gate: 'github_app', project: 'ThinClaw Desktop' },
    },
    {
        id: 'event-run',
        event_type: 'worker.run.started',
        created_at: '2026-06-13T09:12:00Z',
        data: { run_id: 'run-2841', agent: 'docker-agent-01' },
    },
    {
        id: 'event-ci',
        event_type: 'merge_gate.ci.running',
        created_at: '2026-06-13T09:39:00Z',
        data: { check: 'backend / cargo test' },
    },
];
