use crate::sidecar::SidecarManager;
use std::io::Write;
use tauri::AppHandle;
use tauri::Manager;
use tauri::State;
use tauri_plugin_shell::ShellExt;
use tempfile::NamedTempFile;

#[tauri::command]
#[specta::specta]
pub async fn transcribe_audio(
    app: AppHandle,
    state: State<'_, SidecarManager>,
    audio_bytes: Vec<u8>,
) -> Result<String, String> {
    // 1. Get Model
    let model_path = state.get_stt_model().ok_or("STT Model not selected")?;

    // 2. Write audio to temp file
    let mut temp_file =
        NamedTempFile::new().map_err(|e| format!("Failed to create temp file: {}", e))?;
    temp_file
        .write_all(&audio_bytes)
        .map_err(|e| format!("Failed to write audio: {}", e))?;
    let temp_path = temp_file.path().to_string_lossy().to_string();

    // CHECK FOR RUNNING SERVER FIRST
    let server_config = {
        let guard = state.stt_process.lock().unwrap_or_else(|e| e.into_inner());
        guard.as_ref().map(|p| (p.port, p.token.clone()))
    };

    if let Some((port, token)) = server_config {
        // Use Server
        println!("[stt] Using running server at port {}", port);

        let client = reqwest::Client::new();
        // whisper.cpp server expects input in multipart 'file'
        // Endpoint: /inference

        // We need to re-read the file or just use the bytes we have
        // Using audio_bytes directly is better
        let part = reqwest::multipart::Part::bytes(audio_bytes)
            .file_name("audio.wav")
            .mime_str("audio/wav")
            .map_err(|e| e.to_string())?;

        let form = reqwest::multipart::Form::new().part("file", part);

        let res = client
            .post(format!("http://127.0.0.1:{}/inference", port))
            .header("Authorization", format!("Bearer {}", token))
            .multipart(form)
            .send()
            .await
            .map_err(|e| format!("Server request failed: {}", e))?;

        if !res.status().is_success() {
            return Err(format!(
                "Server returned error {}: {}",
                res.status(),
                res.text().await.unwrap_or_default()
            ));
        }

        // Response is JSON: { "text": "..." }
        #[derive(serde::Deserialize)]
        struct WhisperResponse {
            text: String,
        }

        let json: WhisperResponse = res
            .json()
            .await
            .map_err(|e| format!("Failed to parse JSON: {}", e))?;
        return Ok(json.text.trim().to_string());
    }

    // FALLBACK TO CLI (Offline/Cold Start)
    println!("[stt] Server not running, falling back to CLI");

    // 3. Execute 'whisper' CLI
    // args: -m <model> -f <file> -otxt --no-timestamps
    let mut command = app
        .shell()
        .sidecar("whisper")
        .map_err(|e| format!("Failed to load sidecar: {}", e))?;

    // Inject DYLD_LIBRARY_PATH for macOS to find libwhisper.dylib
    if let Ok(resource_dir) = app.path().resource_dir() {
        let bin_dir = resource_dir.join("bin");
        #[cfg(target_os = "macos")]
        {
            let mut lib_path = bin_dir.to_string_lossy().to_string();
            if let Ok(cwd) = std::env::current_dir() {
                let dev_bin = cwd.join("src-tauri/bin");
                if dev_bin.exists() {
                    lib_path = format!("{}:{}", dev_bin.to_string_lossy(), lib_path);
                }
            }
            command = command.env("DYLD_LIBRARY_PATH", lib_path);
        }
    }

    let output = command
        .args([
            "-m",
            &model_path,
            "-f",
            &temp_path,
            "-otxt",           // Output to text file
            "--no-timestamps", // Just plain text
        ])
        .output()
        .await
        .map_err(|e| format!("Failed to execute whisper: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("Whisper Error: {}", stderr));
    }

    // 4. Read output
    let output_path = format!("{}.txt", temp_path);

    if std::path::Path::new(&output_path).exists() {
        let text = std::fs::read_to_string(&output_path)
            .map_err(|e| format!("Failed to read output: {}", e))?;
        // Cleanup output file
        let _ = std::fs::remove_file(output_path);
        Ok(text.trim().to_string())
    } else {
        Err("No output file generated by whisper".to_string())
    }
}
